name: "Code Scanning - Action"

on:
  push:
  #schedule:
    #- cron: '0 0 * * 0'

jobs:
  CodeQL-Build:

    strategy:
      fail-fast: false

    # CodeQL runs on ubuntu-latest and windows-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      # Override language selection by uncommenting this and choosing your languages
      with:
        languages: java
      
        

    # Command-line programs to run using the OS shell.
    # https://git.io/JvXDl
    # Uncomment the following three lines and modify them (or add more) to
    # build your code if your project uses a compiled language (C/C++, C#, or
    # Java).
    - run: |
       ./mvnw package


    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
